### DISCUSSION TITLE
그지같은 spring cloud config 관련!!!!!!!!!!!!!!!

### DISCUSSION THREAD

**Discussion by silverpoodle** [cca-ffodregamdi/running-hi-back#58] [Trouble Shooting]
<img width="764" alt="image" src="https://github.com/cca-ffodregamdi/running-hi-back/assets/88484476/ea140592-ff4b-4b89-a6e8-bfcd61473ba5">

anyway

repository  2개가 추가로 생겼구용

<img width="771" alt="image" src="https://github.com/cca-ffodregamdi/running-hi-back/assets/88484476/be0269d0-bea5-4898-ba96-34743ea5481c">
yml 파일 하나의 레포지토리에 분리해놓고

```yml
# cloud-config-server = cloud-config 설정 파일 접근

server:
  port: 8888

spring:
  profiles:
    active: dev
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: git@github.com:cca-ffodregamdi/running-hi-cloud-config.git
          ignoreLocalSshSettings: true
          private-key: |
```

```yml
# runninghi = cloud-config-server 에서 값 받아옴 

server:
  port: 8080
  servlet:
    session:
      timeout: 360000s
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  cloud:
    config:
      import: "optional:configserver: http://localhost:8888"
  profiles:
    active: dev
```
-> 어플리케이션 야믈 파일에 이렇게만 설정해주면 필요한 설정값들을 다 받아옵니다

![image](https://github.com/cca-ffodregamdi/running-hi-back/assets/88484476/bbfedafb-cd09-43f6-9dc0-bb732298393c)

### 근데 액션 통과가 안돼!!!!!!!!!!!!!
 
..... 내일 강사님께 피드백 한 번 받아야 할 것 같아요
