### DISCUSSION TITLE
Spring Cloud Config 도입한 gradle.yml 정리

### DISCUSSION THREAD

**Discussion by numerical43** [cca-ffodregamdi/running-hi-back#74] [Trouble Shooting]
### Spring Cloud Config Server - Client Server : Git Actions

application repository의 dev 브랜치에 pull request를 하면 github actions가 실행된다.

우리는 그중에서 Java with Gradle Action을 선택했기 때문에 레포지토리에 있는 gradle.yml 을 통해 action을 실행한다.

gradle.yml에는 `cloud`와 `client`라는 두 개의 job을 실행하는데, 각각의 job은 서로 다른 환경에서 실행된다.  또한 병렬로 처리되도록 해놨기 때문에 두 개의 job은 동시에 실행된다.

> cloud 실행 → (cloud 실행 중) client 실행 → (cloud 실행 중) client 종료 → (client가 종료된 걸 확인) cloud 종료
> 

원래는 위의 순서로 진행하고 싶었으나, 저렇게 실행하는 방법을 찾지 못해서 `sleep`을 통해 각각의 job의 실행 순서가 꼬이지않도록 시간차를 주었다. 

### gradle.yml 정리

- **cloud**
    1. cloud : cloud repository로 checkout
        1. `uses` : 다른 사람이 만들어놓은 actions 사용
        2. cloud repo가 private이기 때문에 토큰을 발급받아서 해당 토큰으로 접근
        3. 토큰은 app repo의 설정에서 repository secrets로 등록 해놔야한다.
            1. setting → secrets and variable → actions → repository secrets
        4. cloud repo 중에서도 master branch에 접근한다.
    2. jdk를 설정해주고 cloud repo의 프로젝트 build
        1. 터미널에서 실행되는데, 권한 문제가 발생할 수 있으므로 chmod로 권한을 부여해준다.
            1. `chmood +x`   : 실행 권한 추가
        2. `gradlew`는 gradle wrapper를 의미한다. gradlew는 새로운 환경에서 프로젝트를 설정할 때 java나 gradle을 설치하지않고 바로 빌드할 수 있게 해주는 역할을 한다.
        3. `gradlew clean build` : 빌드 디렉터리를 삭제한 뒤 다시 빌드한다. clean을 하는 이유는 이전 빌드에서 남은 항목을 정리하여 빌드가 손상되는 것을 방지하기 위함이다.
    3. build 후 생성된 jar 파일 실행
        1. 이때 jar 파일이 백그라운드에서 실행되도록 끝에 `&` 를 붙여야한다.
            1. 백그라운드에서 실행하지않으면 다른 동작을 실행할 수 없다. 여기서는 실행 후 sleep과 kill 명령을 실행하는게 불가능해진다.
        2. 터미널에서 실행되는데, 권한 문제가 발생할 수 있으므로 chmod로 권한을 부여해준다.
        3. `$!` : 가장 최근에 실행한 background 명령의 PID
        4. sleep 명령어로 client의 step이 모두 실행될 수 있도록 충분한 시간을 기다린다. 여기서는 180초를 줬다.
        5.  이전에 `JAR_PID`에 저장했던 프로세스 id를 이용하여 프로세스를 종료한다.
- **client**
    1. client : application repository로 checkout
    2. sleep 명령어로 cloud server가 실행될 때까지 충분히 기다린다.
        1. cloud server가 실행되어야 cloud server를 통해 config 정보들을 가져올 수 있기 때문
        2. 여기서는 60초로 설정해주었다.
    3. jdk 설정하고 mysql을 설정한다.
        1. 이때 데이터베이스의 id와 비밀번호는 repository secrets에 등록해놔야한다.
            1. setting → secrets and variable → actions → repository secrets
    4. test를 실행한다.
        1. 권한 문제가 발생할 수 있으므로 chmod로 권한을 부여해준다.
        2. `—info` : test 실행 시 정보를 출력한다.
    5. build한다.
    6. test 결과를 출력한다. 

<br>

### 관련 스크립트
* gradle.yml 전체
```yaml
name: Java CI with Gradle

# dev 브랜치에 pr 시 actions 실행
on:
  pull_request:
    branches:
      - dev

permissions: write-all

jobs:

  # ! spring cloud config server
  cloud:
    runs-on: ubuntu-latest

    # spring cloud config server repository로 checkout
    steps:
      - name: Checkout Cloud Config Server
        uses: actions/checkout@v3
        with:
          repository: cca-ffodregamdi/running-hi-cloud-server
          token: ${{ secrets.GH_PAT }}    # private repository이므로 토큰을 이용해 접근
          ref: master   # master branch 설정

      # jdk 설정
      - name: Set up JDK 17 in Cloud Config Server
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # build
      - name: Build Spring Cloud Config Server
        run: |
          chmod +x gradlew
          ./gradlew clean build
          ls ./build/libs

      # jar 파일 실행
      - name: Run Spring Cloud Config Server
        # 백그라운드에서 실행 -> 180초 기다린 뒤 종료
        run: |
          chmod +x ./build/libs/running-hi-cloud-server-0.0.1-SNAPSHOT.jar
          java -jar ./build/libs/running-hi-cloud-server-0.0.1-SNAPSHOT.jar & 
          JAR_PID=$!
          sleep 180
          kill $JAR_PID
  

  # ! application server
  client:
    runs-on: ubuntu-latest

    # running-hi-back repository로 checkout
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: cca-ffodregamdi/running-hi-back

      # cloud config server가 실행될 때까지 60초 기다림
      - name: Wait for cloud to run
        run: sleep 60

      # jdk 설정
      - name: Set up JDK 17 in Client
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # mysql 설정
      - name: Setup MySQL
        uses: samin/mysql-action@v1
        with:
          mysql database: 'runninghi'
          mysql user: ${{ secrets.MYSQL_USERNAME }}
          mysql password: ${{ secrets.MYSQL_PASSWORD }}

      # test 실행
      - name: Build and Test with Gradle
        run: |
          chmod +x gradlew
          ls ./gradlew
          ./gradlew --info test

      # build
      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build

      # test 결과 출력
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          junit_files: build/test-results/test/**/*.xml
```

* build.gradle에 추가
```
bootJar {
    duplicatesStrategy = 'exclude'
}
```
